from __future__ import annotations

from pathlib import Path
from typing import Any, Dict
import json

from ts_agl.os.chat_loop import FIRST_CONTACT_SCRIPT, run_first_contact_chat_demo
from ts_agl.os.evidence_dashboard import build_ts_evidence_dashboard
from ts_agl.os.first_contact_demo import run_first_contact_demo
from ts_reasoner.proof_object_examples import build_proof_object_examples
from ts_reasoner.typed_support import canonical_hash


def run_ts_os_v30(root: str | Path = ".") -> Dict[str, Any]:
    base = Path(root)
    chat_session = run_first_contact_chat_demo(FIRST_CONTACT_SCRIPT)
    proof_examples = build_proof_object_examples()
    first_contact = run_first_contact_demo()

    # Build the dashboard after the v30-local components are computed. It also
    # reads any existing v26-v29 artifacts already generated by the scripts.
    dashboard = build_ts_evidence_dashboard(base)

    chat_receipt = chat_session.to_dict()
    checks = {
        "chat_loop_gates_passed": chat_receipt["all_gates_passed"],
        "evidence_dashboard_gates_passed": dashboard["all_gates_passed"],
        "proof_object_examples_visible": proof_examples["all_gates_passed"],
        "first_contact_demo_passed": first_contact["all_gates_passed"],
        "destructive_request_abstains": chat_receipt["metrics"]["destructive_request_abstained"],
        "external_side_effect_blocked": chat_receipt["metrics"]["external_side_effect_blocked"],
        "unconfirmed_write_blocked": chat_receipt["metrics"]["project_operator_unconfirmed_write_blocked"],
        "no_network_calls": dashboard["network_call_performed_count"] == 0,
        "no_external_side_effects": dashboard["external_side_effect_performed_count"] == 0,
        "no_external_llm": dashboard["external_llm_used"] is False,
    }
    receipt = {
        "artifact": "ts_os_v30_receipt",
        "release": "v30.0.0",
        "claim": (
            "TS-OS v30 demonstrates a bounded verifier-first local agent operating loop: "
            "natural language requests are translated into typed, risk-classified operations; "
            "unsafe ambiguity abstains; writes and external effects require confirmation; "
            "typed proof objects explain accepted claims; and every action produces replayable receipts."
        ),
        "components": {
            "chat_loop": chat_receipt,
            "evidence_dashboard": dashboard,
            "proof_object_examples": proof_examples,
            "first_contact_demo": first_contact,
        },
        "evidence_dashboard_hash": canonical_hash(dashboard),
        "checks": checks,
        "external_llm_used": False,
        "external_side_effect_performed_count": dashboard["external_side_effect_performed_count"],
        "network_call_performed_count": dashboard["network_call_performed_count"],
        "candidate_graph_contamination_count": dashboard["candidate_graph_contamination_count"],
        "all_gates_passed": all(checks.values()) and dashboard["candidate_graph_contamination_count"] == 0,
    }
    return receipt


def write_ts_os_v30(
    report_path: str | Path = "artifacts/ts_os_v30_report.json",
    receipt_path: str | Path = "artifacts/ts_os_v30_receipt.json",
) -> Dict[str, Any]:
    base = Path(report_path).resolve().parents[1]
    receipt = run_ts_os_v30(base)
    report = {
        "artifact": "ts_os_v30_report",
        "release": "v30.0.0",
        "checks": receipt["checks"],
        "evidence_dashboard_hash": receipt["evidence_dashboard_hash"],
        "external_llm_used": receipt["external_llm_used"],
        "external_side_effect_performed_count": receipt["external_side_effect_performed_count"],
        "network_call_performed_count": receipt["network_call_performed_count"],
        "candidate_graph_contamination_count": receipt["candidate_graph_contamination_count"],
        "all_gates_passed": receipt["all_gates_passed"],
    }
    report_target = Path(report_path)
    receipt_target = Path(receipt_path)
    report_target.parent.mkdir(parents=True, exist_ok=True)
    receipt_target.parent.mkdir(parents=True, exist_ok=True)
    report_target.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    receipt_target.write_text(json.dumps(receipt, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return report
